---
# connector deployment

- name: deploys the application
  hosts: webservers
  sudo: yes
  vars:
    timestamp: ""

#tasks:
#dummy

#      - name: get statistics jar
#         nexus:
#           nexus: http://10.16.96.11:8081/
#           artifactid: common-types
#           extension: jar
#           repository: Snapshots

#      - maven_artifact:
#          group_id: de.drgueldener.common
#          artifact_id: common-types
#          repository_url: 'http://10.16.96.11:8081/repository/Snapshots'
#          username: admin
#          password: KLNMJL24&f!aa
#          dest: /opt/common-types/

#    - name: copy the jar
#      copy: src=/var/lib/jenkins/.m2/repository/com/example/SpringBootApplication/1.0.0-SNAPSHOT/SpringBootApplication-1.0.0-SNAPSHOT.jar dest=/opt/SpringBootApplication-1.0.0-SNAPSHOT.jar

#    - name: unlink the current app
#      file: path=/home/ubuntu/app.jar state=absent

#    - name: link to the newly deployed app
#      file: path=/opt/SpringBootApplication-1.0.0-SNAPSHOT.jar src=/opt/SpringBootApplication-1.0.0-SNAPSHOT.jar state=link

#    - name: stops running app
#      sudo: yes
#      service: name=app state=stopped

#    - name: starts the app
#      sudo: yes
#      command: java -jar opt/SpringBootApplication-1.0.0-SNAPSHOT.jar